export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          slug: string;
          app_url: string;
          description: string | null;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          slug: string;
          app_url: string;
          description?: string | null;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          slug?: string;
          app_url?: string;
          description?: string | null;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      tests: {
        Row: {
          id: string;
          project_id: string;
          name: string;
          description: string | null;
          steps: Json;
          tags: string[];
          priority: 'critical' | 'high' | 'medium' | 'low';
          is_active: boolean;
          source: 'manual' | 'discovered' | 'generated' | 'imported';
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          name: string;
          description?: string | null;
          steps?: Json;
          tags?: string[];
          priority?: 'critical' | 'high' | 'medium' | 'low';
          is_active?: boolean;
          source?: 'manual' | 'discovered' | 'generated' | 'imported';
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          name?: string;
          description?: string | null;
          steps?: Json;
          tags?: string[];
          priority?: 'critical' | 'high' | 'medium' | 'low';
          is_active?: boolean;
          source?: 'manual' | 'discovered' | 'generated' | 'imported';
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      test_runs: {
        Row: {
          id: string;
          project_id: string;
          name: string | null;
          trigger: 'manual' | 'scheduled' | 'webhook' | 'ci';
          status: 'pending' | 'running' | 'passed' | 'failed' | 'cancelled';
          app_url: string;
          environment: string;
          browser: string;
          total_tests: number;
          passed_tests: number;
          failed_tests: number;
          skipped_tests: number;
          duration_ms: number | null;
          started_at: string | null;
          completed_at: string | null;
          triggered_by: string | null;
          ci_metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          name?: string | null;
          trigger?: 'manual' | 'scheduled' | 'webhook' | 'ci';
          status?: 'pending' | 'running' | 'passed' | 'failed' | 'cancelled';
          app_url: string;
          environment?: string;
          browser?: string;
          total_tests?: number;
          passed_tests?: number;
          failed_tests?: number;
          skipped_tests?: number;
          duration_ms?: number | null;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          ci_metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          name?: string | null;
          trigger?: 'manual' | 'scheduled' | 'webhook' | 'ci';
          status?: 'pending' | 'running' | 'passed' | 'failed' | 'cancelled';
          app_url?: string;
          environment?: string;
          browser?: string;
          total_tests?: number;
          passed_tests?: number;
          failed_tests?: number;
          skipped_tests?: number;
          duration_ms?: number | null;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          ci_metadata?: Json;
          created_at?: string;
        };
      };
      test_results: {
        Row: {
          id: string;
          test_run_id: string;
          test_id: string | null;
          name: string;
          status: 'pending' | 'running' | 'passed' | 'failed' | 'skipped';
          duration_ms: number | null;
          error_message: string | null;
          error_stack: string | null;
          steps_completed: number;
          steps_total: number;
          step_results: Json;
          retry_count: number;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          test_run_id: string;
          test_id?: string | null;
          name: string;
          status?: 'pending' | 'running' | 'passed' | 'failed' | 'skipped';
          duration_ms?: number | null;
          error_message?: string | null;
          error_stack?: string | null;
          steps_completed?: number;
          steps_total?: number;
          step_results?: Json;
          retry_count?: number;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          test_run_id?: string;
          test_id?: string | null;
          name?: string;
          status?: 'pending' | 'running' | 'passed' | 'failed' | 'skipped';
          duration_ms?: number | null;
          error_message?: string | null;
          error_stack?: string | null;
          steps_completed?: number;
          steps_total?: number;
          step_results?: Json;
          retry_count?: number;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
      };
      discovery_sessions: {
        Row: {
          id: string;
          project_id: string;
          status: 'pending' | 'running' | 'completed' | 'failed';
          app_url: string;
          pages_found: number;
          flows_found: number;
          forms_found: number;
          elements_found: number;
          started_at: string | null;
          completed_at: string | null;
          triggered_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          status?: 'pending' | 'running' | 'completed' | 'failed';
          app_url: string;
          pages_found?: number;
          flows_found?: number;
          forms_found?: number;
          elements_found?: number;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          status?: 'pending' | 'running' | 'completed' | 'failed';
          app_url?: string;
          pages_found?: number;
          flows_found?: number;
          forms_found?: number;
          elements_found?: number;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          created_at?: string;
        };
      };
      discovered_pages: {
        Row: {
          id: string;
          discovery_session_id: string;
          project_id: string;
          url: string;
          title: string | null;
          page_type: string | null;
          element_count: number;
          form_count: number;
          link_count: number;
          screenshot_url: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          discovery_session_id: string;
          project_id: string;
          url: string;
          title?: string | null;
          page_type?: string | null;
          element_count?: number;
          form_count?: number;
          link_count?: number;
          screenshot_url?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          discovery_session_id?: string;
          project_id?: string;
          url?: string;
          title?: string | null;
          page_type?: string | null;
          element_count?: number;
          form_count?: number;
          link_count?: number;
          screenshot_url?: string | null;
          metadata?: Json;
          created_at?: string;
        };
      };
      discovered_flows: {
        Row: {
          id: string;
          discovery_session_id: string;
          project_id: string;
          name: string;
          description: string | null;
          steps: Json;
          step_count: number;
          priority: 'critical' | 'high' | 'medium' | 'low';
          converted_to_test_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          discovery_session_id: string;
          project_id: string;
          name: string;
          description?: string | null;
          steps?: Json;
          step_count?: number;
          priority?: 'critical' | 'high' | 'medium' | 'low';
          converted_to_test_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          discovery_session_id?: string;
          project_id?: string;
          name?: string;
          description?: string | null;
          steps?: Json;
          step_count?: number;
          priority?: 'critical' | 'high' | 'medium' | 'low';
          converted_to_test_id?: string | null;
          created_at?: string;
        };
      };
      visual_baselines: {
        Row: {
          id: string;
          project_id: string;
          name: string;
          selector: string | null;
          page_url: string;
          viewport: string;
          screenshot_url: string;
          screenshot_hash: string | null;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          name: string;
          selector?: string | null;
          page_url: string;
          viewport?: string;
          screenshot_url: string;
          screenshot_hash?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          name?: string;
          selector?: string | null;
          page_url?: string;
          viewport?: string;
          screenshot_url?: string;
          screenshot_hash?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
      };
      visual_comparisons: {
        Row: {
          id: string;
          project_id: string;
          baseline_id: string | null;
          name: string;
          status: 'match' | 'mismatch' | 'new' | 'pending' | 'error';
          match_percentage: number | null;
          difference_count: number;
          baseline_url: string | null;
          current_url: string;
          diff_url: string | null;
          threshold: number;
          approved_by: string | null;
          approved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          baseline_id?: string | null;
          name: string;
          status?: 'match' | 'mismatch' | 'new' | 'pending' | 'error';
          match_percentage?: number | null;
          difference_count?: number;
          baseline_url?: string | null;
          current_url: string;
          diff_url?: string | null;
          threshold?: number;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          baseline_id?: string | null;
          name?: string;
          status?: 'match' | 'mismatch' | 'new' | 'pending' | 'error';
          match_percentage?: number | null;
          difference_count?: number;
          baseline_url?: string | null;
          current_url?: string;
          diff_url?: string | null;
          threshold?: number;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
        };
      };
      ai_insights: {
        Row: {
          id: string;
          project_id: string;
          insight_type: 'prediction' | 'anomaly' | 'suggestion' | 'understanding';
          severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
          title: string;
          description: string;
          confidence: number;
          affected_area: string | null;
          suggested_action: string | null;
          action_url: string | null;
          related_test_ids: string[] | null;
          is_resolved: boolean;
          resolved_at: string | null;
          resolved_by: string | null;
          expires_at: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          insight_type: 'prediction' | 'anomaly' | 'suggestion' | 'understanding';
          severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
          title: string;
          description: string;
          confidence: number;
          affected_area?: string | null;
          suggested_action?: string | null;
          action_url?: string | null;
          related_test_ids?: string[] | null;
          is_resolved?: boolean;
          resolved_at?: string | null;
          resolved_by?: string | null;
          expires_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          insight_type?: 'prediction' | 'anomaly' | 'suggestion' | 'understanding';
          severity?: 'critical' | 'high' | 'medium' | 'low' | 'info';
          title?: string;
          description?: string;
          confidence?: number;
          affected_area?: string | null;
          suggested_action?: string | null;
          action_url?: string | null;
          related_test_ids?: string[] | null;
          is_resolved?: boolean;
          resolved_at?: string | null;
          resolved_by?: string | null;
          expires_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
      };
      quality_audits: {
        Row: {
          id: string;
          project_id: string;
          url: string;
          status: 'pending' | 'running' | 'completed' | 'failed';
          accessibility_score: number | null;
          performance_score: number | null;
          best_practices_score: number | null;
          seo_score: number | null;
          lcp_ms: number | null;
          fid_ms: number | null;
          cls: number | null;
          ttfb_ms: number | null;
          fcp_ms: number | null;
          tti_ms: number | null;
          started_at: string | null;
          completed_at: string | null;
          triggered_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          url: string;
          status?: 'pending' | 'running' | 'completed' | 'failed';
          accessibility_score?: number | null;
          performance_score?: number | null;
          best_practices_score?: number | null;
          seo_score?: number | null;
          lcp_ms?: number | null;
          fid_ms?: number | null;
          cls?: number | null;
          ttfb_ms?: number | null;
          fcp_ms?: number | null;
          tti_ms?: number | null;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          url?: string;
          status?: 'pending' | 'running' | 'completed' | 'failed';
          accessibility_score?: number | null;
          performance_score?: number | null;
          best_practices_score?: number | null;
          seo_score?: number | null;
          lcp_ms?: number | null;
          fid_ms?: number | null;
          cls?: number | null;
          ttfb_ms?: number | null;
          fcp_ms?: number | null;
          tti_ms?: number | null;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          created_at?: string;
        };
      };
      accessibility_issues: {
        Row: {
          id: string;
          audit_id: string;
          rule: string;
          severity: 'critical' | 'serious' | 'moderate' | 'minor';
          element_selector: string | null;
          description: string;
          suggested_fix: string | null;
          wcag_criteria: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          audit_id: string;
          rule: string;
          severity: 'critical' | 'serious' | 'moderate' | 'minor';
          element_selector?: string | null;
          description: string;
          suggested_fix?: string | null;
          wcag_criteria?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          audit_id?: string;
          rule?: string;
          severity?: 'critical' | 'serious' | 'moderate' | 'minor';
          element_selector?: string | null;
          description?: string;
          suggested_fix?: string | null;
          wcag_criteria?: string[] | null;
          created_at?: string;
        };
      };
      performance_tests: {
        Row: {
          id: string;
          project_id: string;
          url: string;
          device: 'mobile' | 'desktop';
          status: 'pending' | 'running' | 'completed' | 'failed';
          lcp_ms: number | null;
          fid_ms: number | null;
          cls: number | null;
          inp_ms: number | null;
          ttfb_ms: number | null;
          fcp_ms: number | null;
          speed_index: number | null;
          tti_ms: number | null;
          tbt_ms: number | null;
          total_requests: number | null;
          total_transfer_size_kb: number | null;
          js_execution_time_ms: number | null;
          dom_content_loaded_ms: number | null;
          load_time_ms: number | null;
          performance_score: number | null;
          accessibility_score: number | null;
          best_practices_score: number | null;
          seo_score: number | null;
          overall_grade: 'excellent' | 'good' | 'needs_work' | 'poor' | null;
          recommendations: string[];
          issues: Json;
          summary: string | null;
          started_at: string | null;
          completed_at: string | null;
          triggered_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          url: string;
          device?: 'mobile' | 'desktop';
          status?: 'pending' | 'running' | 'completed' | 'failed';
          lcp_ms?: number | null;
          fid_ms?: number | null;
          cls?: number | null;
          inp_ms?: number | null;
          ttfb_ms?: number | null;
          fcp_ms?: number | null;
          speed_index?: number | null;
          tti_ms?: number | null;
          tbt_ms?: number | null;
          total_requests?: number | null;
          total_transfer_size_kb?: number | null;
          js_execution_time_ms?: number | null;
          dom_content_loaded_ms?: number | null;
          load_time_ms?: number | null;
          performance_score?: number | null;
          accessibility_score?: number | null;
          best_practices_score?: number | null;
          seo_score?: number | null;
          overall_grade?: 'excellent' | 'good' | 'needs_work' | 'poor' | null;
          recommendations?: string[];
          issues?: Json;
          summary?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          url?: string;
          device?: 'mobile' | 'desktop';
          status?: 'pending' | 'running' | 'completed' | 'failed';
          lcp_ms?: number | null;
          fid_ms?: number | null;
          cls?: number | null;
          inp_ms?: number | null;
          ttfb_ms?: number | null;
          fcp_ms?: number | null;
          speed_index?: number | null;
          tti_ms?: number | null;
          tbt_ms?: number | null;
          total_requests?: number | null;
          total_transfer_size_kb?: number | null;
          js_execution_time_ms?: number | null;
          dom_content_loaded_ms?: number | null;
          load_time_ms?: number | null;
          performance_score?: number | null;
          accessibility_score?: number | null;
          best_practices_score?: number | null;
          seo_score?: number | null;
          overall_grade?: 'excellent' | 'good' | 'needs_work' | 'poor' | null;
          recommendations?: string[];
          issues?: Json;
          summary?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          created_at?: string;
        };
      };
      global_tests: {
        Row: {
          id: string;
          project_id: string;
          url: string;
          status: 'pending' | 'running' | 'completed' | 'failed';
          avg_latency_ms: number | null;
          avg_ttfb_ms: number | null;
          success_rate: number | null;
          slow_regions: number;
          failed_regions: number;
          started_at: string | null;
          completed_at: string | null;
          triggered_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          url: string;
          status?: 'pending' | 'running' | 'completed' | 'failed';
          avg_latency_ms?: number | null;
          avg_ttfb_ms?: number | null;
          success_rate?: number | null;
          slow_regions?: number;
          failed_regions?: number;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          url?: string;
          status?: 'pending' | 'running' | 'completed' | 'failed';
          avg_latency_ms?: number | null;
          avg_ttfb_ms?: number | null;
          success_rate?: number | null;
          slow_regions?: number;
          failed_regions?: number;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          created_at?: string;
        };
      };
      global_test_results: {
        Row: {
          id: string;
          global_test_id: string;
          region_code: string;
          city: string;
          status: 'success' | 'error' | 'slow' | 'timeout';
          latency_ms: number | null;
          ttfb_ms: number | null;
          page_load_ms: number | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          global_test_id: string;
          region_code: string;
          city: string;
          status: 'success' | 'error' | 'slow' | 'timeout';
          latency_ms?: number | null;
          ttfb_ms?: number | null;
          page_load_ms?: number | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          global_test_id?: string;
          region_code?: string;
          city?: string;
          status?: 'success' | 'error' | 'slow' | 'timeout';
          latency_ms?: number | null;
          ttfb_ms?: number | null;
          page_load_ms?: number | null;
          error_message?: string | null;
          created_at?: string;
        };
      };
      integrations: {
        Row: {
          id: string;
          user_id: string;
          platform: string;
          platform_type: 'cicd' | 'observability' | 'notification';
          is_connected: boolean;
          config: Json;
          last_sync_at: string | null;
          sync_status: string | null;
          data_points_synced: number;
          features_enabled: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          platform: string;
          platform_type: 'cicd' | 'observability' | 'notification';
          is_connected?: boolean;
          config?: Json;
          last_sync_at?: string | null;
          sync_status?: string | null;
          data_points_synced?: number;
          features_enabled?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          platform?: string;
          platform_type?: 'cicd' | 'observability' | 'notification';
          is_connected?: boolean;
          config?: Json;
          last_sync_at?: string | null;
          sync_status?: string | null;
          data_points_synced?: number;
          features_enabled?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      project_stats: {
        Row: {
          id: string;
          project_id: string;
          total_tests: number;
          total_runs: number;
          total_passed: number;
          total_failed: number;
          avg_pass_rate: number;
          avg_duration_ms: number;
          last_run_at: string | null;
          last_run_status: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          total_tests?: number;
          total_runs?: number;
          total_passed?: number;
          total_failed?: number;
          avg_pass_rate?: number;
          avg_duration_ms?: number;
          last_run_at?: string | null;
          last_run_status?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          total_tests?: number;
          total_runs?: number;
          total_passed?: number;
          total_failed?: number;
          avg_pass_rate?: number;
          avg_duration_ms?: number;
          last_run_at?: string | null;
          last_run_status?: string | null;
          updated_at?: string;
        };
      };
      daily_stats: {
        Row: {
          id: string;
          project_id: string;
          date: string;
          runs: number;
          passed: number;
          failed: number;
          avg_duration_ms: number;
        };
        Insert: {
          id?: string;
          project_id: string;
          date?: string;
          runs?: number;
          passed?: number;
          failed?: number;
          avg_duration_ms?: number;
        };
        Update: {
          id?: string;
          project_id?: string;
          date?: string;
          runs?: number;
          passed?: number;
          failed?: number;
          avg_duration_ms?: number;
        };
      };
      chat_conversations: {
        Row: {
          id: string;
          project_id: string | null;
          user_id: string;
          title: string | null;
          preview: string | null;
          message_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id?: string | null;
          user_id: string;
          title?: string | null;
          preview?: string | null;
          message_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string | null;
          user_id?: string;
          title?: string | null;
          preview?: string | null;
          message_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      chat_messages: {
        Row: {
          id: string;
          conversation_id: string;
          role: 'user' | 'assistant' | 'system';
          content: string;
          tool_invocations: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          role: 'user' | 'assistant' | 'system';
          content: string;
          tool_invocations?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          role?: 'user' | 'assistant' | 'system';
          content?: string;
          tool_invocations?: Json | null;
          created_at?: string;
        };
      };
      // ============================================
      // QUALITY INTELLIGENCE PLATFORM
      // ============================================
      production_events: {
        Row: {
          id: string;
          project_id: string;
          integration_id: string | null;
          source: 'sentry' | 'datadog' | 'fullstory' | 'logrocket' | 'newrelic' | 'bugsnag' | 'rollbar' | 'custom';
          external_id: string;
          external_url: string | null;
          event_type: 'error' | 'exception' | 'crash' | 'performance' | 'user_feedback' | 'rage_click' | 'dead_click';
          severity: 'fatal' | 'error' | 'warning' | 'info';
          title: string;
          message: string | null;
          stack_trace: string | null;
          fingerprint: string | null;
          url: string | null;
          component: string | null;
          user_action: string | null;
          browser: string | null;
          os: string | null;
          device_type: 'desktop' | 'mobile' | 'tablet' | null;
          occurrence_count: number;
          affected_users: number;
          first_seen_at: string;
          last_seen_at: string;
          ai_analysis: Json | null;
          root_cause: string | null;
          suggested_fix: string | null;
          status: 'new' | 'analyzing' | 'test_generated' | 'test_pending_review' | 'resolved' | 'ignored' | 'wont_fix';
          resolved_at: string | null;
          resolved_by: string | null;
          raw_payload: Json;
          tags: string[];
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          integration_id?: string | null;
          source: 'sentry' | 'datadog' | 'fullstory' | 'logrocket' | 'newrelic' | 'bugsnag' | 'rollbar' | 'custom';
          external_id: string;
          external_url?: string | null;
          event_type: 'error' | 'exception' | 'crash' | 'performance' | 'user_feedback' | 'rage_click' | 'dead_click';
          severity: 'fatal' | 'error' | 'warning' | 'info';
          title: string;
          message?: string | null;
          stack_trace?: string | null;
          fingerprint?: string | null;
          url?: string | null;
          component?: string | null;
          user_action?: string | null;
          browser?: string | null;
          os?: string | null;
          device_type?: 'desktop' | 'mobile' | 'tablet' | null;
          occurrence_count?: number;
          affected_users?: number;
          first_seen_at?: string;
          last_seen_at?: string;
          ai_analysis?: Json | null;
          root_cause?: string | null;
          suggested_fix?: string | null;
          status?: 'new' | 'analyzing' | 'test_generated' | 'test_pending_review' | 'resolved' | 'ignored' | 'wont_fix';
          resolved_at?: string | null;
          resolved_by?: string | null;
          raw_payload?: Json;
          tags?: string[];
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          integration_id?: string | null;
          source?: 'sentry' | 'datadog' | 'fullstory' | 'logrocket' | 'newrelic' | 'bugsnag' | 'rollbar' | 'custom';
          external_id?: string;
          external_url?: string | null;
          event_type?: 'error' | 'exception' | 'crash' | 'performance' | 'user_feedback' | 'rage_click' | 'dead_click';
          severity?: 'fatal' | 'error' | 'warning' | 'info';
          title?: string;
          message?: string | null;
          stack_trace?: string | null;
          fingerprint?: string | null;
          url?: string | null;
          component?: string | null;
          user_action?: string | null;
          browser?: string | null;
          os?: string | null;
          device_type?: 'desktop' | 'mobile' | 'tablet' | null;
          occurrence_count?: number;
          affected_users?: number;
          first_seen_at?: string;
          last_seen_at?: string;
          ai_analysis?: Json | null;
          root_cause?: string | null;
          suggested_fix?: string | null;
          status?: 'new' | 'analyzing' | 'test_generated' | 'test_pending_review' | 'resolved' | 'ignored' | 'wont_fix';
          resolved_at?: string | null;
          resolved_by?: string | null;
          raw_payload?: Json;
          tags?: string[];
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      generated_tests: {
        Row: {
          id: string;
          project_id: string;
          production_event_id: string | null;
          error_pattern_id: string | null;
          name: string;
          description: string | null;
          test_type: 'e2e' | 'integration' | 'unit' | 'visual' | 'accessibility';
          framework: string;
          test_code: string;
          test_file_path: string | null;
          steps: Json;
          assertions: Json;
          confidence_score: number;
          quality_score: number | null;
          status: 'pending' | 'approved' | 'rejected' | 'modified' | 'deployed';
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_notes: string | null;
          github_pr_url: string | null;
          github_pr_number: number | null;
          github_pr_status: 'draft' | 'open' | 'merged' | 'closed' | null;
          deployed_at: string | null;
          converted_to_test_id: string | null;
          times_run: number;
          times_passed: number;
          times_failed: number;
          prevented_incidents: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          production_event_id?: string | null;
          error_pattern_id?: string | null;
          name: string;
          description?: string | null;
          test_type: 'e2e' | 'integration' | 'unit' | 'visual' | 'accessibility';
          framework?: string;
          test_code: string;
          test_file_path?: string | null;
          steps?: Json;
          assertions?: Json;
          confidence_score: number;
          quality_score?: number | null;
          status?: 'pending' | 'approved' | 'rejected' | 'modified' | 'deployed';
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_notes?: string | null;
          github_pr_url?: string | null;
          github_pr_number?: number | null;
          github_pr_status?: 'draft' | 'open' | 'merged' | 'closed' | null;
          deployed_at?: string | null;
          converted_to_test_id?: string | null;
          times_run?: number;
          times_passed?: number;
          times_failed?: number;
          prevented_incidents?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          production_event_id?: string | null;
          error_pattern_id?: string | null;
          name?: string;
          description?: string | null;
          test_type?: 'e2e' | 'integration' | 'unit' | 'visual' | 'accessibility';
          framework?: string;
          test_code?: string;
          test_file_path?: string | null;
          steps?: Json;
          assertions?: Json;
          confidence_score?: number;
          quality_score?: number | null;
          status?: 'pending' | 'approved' | 'rejected' | 'modified' | 'deployed';
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_notes?: string | null;
          github_pr_url?: string | null;
          github_pr_number?: number | null;
          github_pr_status?: 'draft' | 'open' | 'merged' | 'closed' | null;
          deployed_at?: string | null;
          converted_to_test_id?: string | null;
          times_run?: number;
          times_passed?: number;
          times_failed?: number;
          prevented_incidents?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      risk_scores: {
        Row: {
          id: string;
          project_id: string;
          entity_type: 'page' | 'component' | 'flow' | 'endpoint' | 'feature';
          entity_identifier: string;
          entity_name: string | null;
          overall_risk_score: number;
          error_frequency_score: number;
          error_severity_score: number;
          test_coverage_score: number;
          change_frequency_score: number;
          user_impact_score: number;
          factors: Json;
          previous_score: number | null;
          score_trend: 'improving' | 'stable' | 'degrading' | null;
          recommendations: Json;
          priority_tests_needed: string[];
          last_calculated_at: string;
          calculation_version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          entity_type: 'page' | 'component' | 'flow' | 'endpoint' | 'feature';
          entity_identifier: string;
          entity_name?: string | null;
          overall_risk_score: number;
          error_frequency_score?: number;
          error_severity_score?: number;
          test_coverage_score?: number;
          change_frequency_score?: number;
          user_impact_score?: number;
          factors?: Json;
          previous_score?: number | null;
          score_trend?: 'improving' | 'stable' | 'degrading' | null;
          recommendations?: Json;
          priority_tests_needed?: string[];
          last_calculated_at?: string;
          calculation_version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          entity_type?: 'page' | 'component' | 'flow' | 'endpoint' | 'feature';
          entity_identifier?: string;
          entity_name?: string | null;
          overall_risk_score?: number;
          error_frequency_score?: number;
          error_severity_score?: number;
          test_coverage_score?: number;
          change_frequency_score?: number;
          user_impact_score?: number;
          factors?: Json;
          previous_score?: number | null;
          score_trend?: 'improving' | 'stable' | 'degrading' | null;
          recommendations?: Json;
          priority_tests_needed?: string[];
          last_calculated_at?: string;
          calculation_version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      test_generation_jobs: {
        Row: {
          id: string;
          project_id: string;
          production_event_id: string | null;
          status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
          job_type: 'single_error' | 'pattern_batch' | 'coverage_gap' | 'scheduled';
          ai_model: string;
          prompt_tokens: number;
          completion_tokens: number;
          total_cost_cents: number;
          tests_generated: number;
          tests_approved: number;
          error_message: string | null;
          started_at: string | null;
          completed_at: string | null;
          duration_ms: number | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          production_event_id?: string | null;
          status?: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
          job_type: 'single_error' | 'pattern_batch' | 'coverage_gap' | 'scheduled';
          ai_model?: string;
          prompt_tokens?: number;
          completion_tokens?: number;
          total_cost_cents?: number;
          tests_generated?: number;
          tests_approved?: number;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          duration_ms?: number | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          production_event_id?: string | null;
          status?: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
          job_type?: 'single_error' | 'pattern_batch' | 'coverage_gap' | 'scheduled';
          ai_model?: string;
          prompt_tokens?: number;
          completion_tokens?: number;
          total_cost_cents?: number;
          tests_generated?: number;
          tests_approved?: number;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          duration_ms?: number | null;
          metadata?: Json;
          created_at?: string;
        };
      };
      quality_intelligence_stats: {
        Row: {
          id: string;
          project_id: string;
          total_production_events: number;
          events_last_24h: number;
          events_last_7d: number;
          events_last_30d: number;
          tests_generated: number;
          tests_approved: number;
          tests_deployed: number;
          incidents_prevented: number;
          estimated_time_saved_hours: number;
          high_risk_components: number;
          components_with_tests: number;
          coverage_improvement_percent: number;
          active_integrations: number;
          last_event_received_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          total_production_events?: number;
          events_last_24h?: number;
          events_last_7d?: number;
          events_last_30d?: number;
          tests_generated?: number;
          tests_approved?: number;
          tests_deployed?: number;
          incidents_prevented?: number;
          estimated_time_saved_hours?: number;
          high_risk_components?: number;
          components_with_tests?: number;
          coverage_improvement_percent?: number;
          active_integrations?: number;
          last_event_received_at?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          total_production_events?: number;
          events_last_24h?: number;
          events_last_7d?: number;
          events_last_30d?: number;
          tests_generated?: number;
          tests_approved?: number;
          tests_deployed?: number;
          incidents_prevented?: number;
          estimated_time_saved_hours?: number;
          high_risk_components?: number;
          components_with_tests?: number;
          coverage_improvement_percent?: number;
          active_integrations?: number;
          last_event_received_at?: string | null;
          updated_at?: string;
        };
      };
      // ============================================
      // CLAUDE CODE PLUGIN MONITORING
      // ============================================
      plugin_events: {
        Row: {
          id: string;
          user_id: string;
          project_id: string | null;
          session_id: string;
          event_type: 'command' | 'skill' | 'agent' | 'hook' | 'mcp_tool' | 'error' | 'session_start' | 'session_end';
          event_name: string;
          status: 'started' | 'completed' | 'failed' | 'cancelled';
          started_at: string;
          completed_at: string | null;
          duration_ms: number | null;
          input_data: Json;
          output_data: Json;
          error_message: string | null;
          git_branch: string | null;
          git_commit: string | null;
          git_repo: string | null;
          workspace_path: string | null;
          file_paths: string[] | null;
          plugin_version: string | null;
          claude_code_version: string | null;
          os_platform: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          project_id?: string | null;
          session_id: string;
          event_type: 'command' | 'skill' | 'agent' | 'hook' | 'mcp_tool' | 'error' | 'session_start' | 'session_end';
          event_name: string;
          status?: 'started' | 'completed' | 'failed' | 'cancelled';
          started_at?: string;
          completed_at?: string | null;
          duration_ms?: number | null;
          input_data?: Json;
          output_data?: Json;
          error_message?: string | null;
          git_branch?: string | null;
          git_commit?: string | null;
          git_repo?: string | null;
          workspace_path?: string | null;
          file_paths?: string[] | null;
          plugin_version?: string | null;
          claude_code_version?: string | null;
          os_platform?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string | null;
          session_id?: string;
          event_type?: 'command' | 'skill' | 'agent' | 'hook' | 'mcp_tool' | 'error' | 'session_start' | 'session_end';
          event_name?: string;
          status?: 'started' | 'completed' | 'failed' | 'cancelled';
          started_at?: string;
          completed_at?: string | null;
          duration_ms?: number | null;
          input_data?: Json;
          output_data?: Json;
          error_message?: string | null;
          git_branch?: string | null;
          git_commit?: string | null;
          git_repo?: string | null;
          workspace_path?: string | null;
          file_paths?: string[] | null;
          plugin_version?: string | null;
          claude_code_version?: string | null;
          os_platform?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      plugin_sessions: {
        Row: {
          id: string;
          user_id: string;
          project_id: string | null;
          session_id: string;
          started_at: string;
          ended_at: string | null;
          duration_ms: number | null;
          total_events: number;
          commands_executed: number;
          skills_activated: number;
          agents_invoked: number;
          hooks_triggered: number;
          mcp_calls: number;
          errors_count: number;
          git_repo: string | null;
          git_branch: string | null;
          workspace_path: string | null;
          plugin_version: string | null;
          claude_code_version: string | null;
          os_platform: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          project_id?: string | null;
          session_id: string;
          started_at: string;
          ended_at?: string | null;
          duration_ms?: number | null;
          total_events?: number;
          commands_executed?: number;
          skills_activated?: number;
          agents_invoked?: number;
          hooks_triggered?: number;
          mcp_calls?: number;
          errors_count?: number;
          git_repo?: string | null;
          git_branch?: string | null;
          workspace_path?: string | null;
          plugin_version?: string | null;
          claude_code_version?: string | null;
          os_platform?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string | null;
          session_id?: string;
          started_at?: string;
          ended_at?: string | null;
          duration_ms?: number | null;
          total_events?: number;
          commands_executed?: number;
          skills_activated?: number;
          agents_invoked?: number;
          hooks_triggered?: number;
          mcp_calls?: number;
          errors_count?: number;
          git_repo?: string | null;
          git_branch?: string | null;
          workspace_path?: string | null;
          plugin_version?: string | null;
          claude_code_version?: string | null;
          os_platform?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      plugin_metrics: {
        Row: {
          id: string;
          user_id: string | null;
          project_id: string | null;
          time_bucket: string;
          bucket_size: 'hour' | 'day' | 'week';
          command_count: number;
          skill_count: number;
          agent_count: number;
          hook_count: number;
          mcp_call_count: number;
          error_count: number;
          session_count: number;
          avg_duration_ms: number | null;
          p50_duration_ms: number | null;
          p95_duration_ms: number | null;
          p99_duration_ms: number | null;
          top_commands: Json;
          top_skills: Json;
          top_agents: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          project_id?: string | null;
          time_bucket: string;
          bucket_size?: 'hour' | 'day' | 'week';
          command_count?: number;
          skill_count?: number;
          agent_count?: number;
          hook_count?: number;
          mcp_call_count?: number;
          error_count?: number;
          session_count?: number;
          avg_duration_ms?: number | null;
          p50_duration_ms?: number | null;
          p95_duration_ms?: number | null;
          p99_duration_ms?: number | null;
          top_commands?: Json;
          top_skills?: Json;
          top_agents?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          project_id?: string | null;
          time_bucket?: string;
          bucket_size?: 'hour' | 'day' | 'week';
          command_count?: number;
          skill_count?: number;
          agent_count?: number;
          hook_count?: number;
          mcp_call_count?: number;
          error_count?: number;
          session_count?: number;
          avg_duration_ms?: number | null;
          p50_duration_ms?: number | null;
          p95_duration_ms?: number | null;
          p99_duration_ms?: number | null;
          top_commands?: Json;
          top_skills?: Json;
          top_agents?: Json;
          created_at?: string;
        };
      };
    };
  };
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];

// Commonly used types
export type Project = Tables<'projects'>;
export type Test = Tables<'tests'>;
export type TestRun = Tables<'test_runs'>;
export type TestResult = Tables<'test_results'>;
export type DiscoverySession = Tables<'discovery_sessions'>;
export type DiscoveredPage = Tables<'discovered_pages'>;
export type DiscoveredFlow = Tables<'discovered_flows'>;
export type VisualBaseline = Tables<'visual_baselines'>;
export type VisualComparison = Tables<'visual_comparisons'>;
export type AIInsight = Tables<'ai_insights'>;
export type QualityAudit = Tables<'quality_audits'>;
export type AccessibilityIssue = Tables<'accessibility_issues'>;
export type PerformanceTest = Tables<'performance_tests'>;
export type GlobalTest = Tables<'global_tests'>;
export type GlobalTestResult = Tables<'global_test_results'>;
export type Integration = Tables<'integrations'>;
export type ProjectStats = Tables<'project_stats'>;
export type DailyStats = Tables<'daily_stats'>;
export type ChatConversation = Tables<'chat_conversations'>;
export type ChatMessage = Tables<'chat_messages'>;

// Quality Intelligence Platform types
export type ProductionEvent = Tables<'production_events'>;
export type GeneratedTest = Tables<'generated_tests'>;
export type RiskScore = Tables<'risk_scores'>;
export type TestGenerationJob = Tables<'test_generation_jobs'>;
export type QualityIntelligenceStats = Tables<'quality_intelligence_stats'>;

// Claude Code Plugin Monitoring types
export type PluginEvent = Tables<'plugin_events'>;
export type PluginSession = Tables<'plugin_sessions'>;
export type PluginMetrics = Tables<'plugin_metrics'>;

// Security Scan types (used by frontend, backed by API)
export type VulnerabilitySeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';
export type VulnerabilityCategory =
  | 'A01:2021-Broken Access Control'
  | 'A02:2021-Cryptographic Failures'
  | 'A03:2021-Injection'
  | 'A05:2021-Security Misconfiguration'
  | 'A06:2021-Vulnerable and Outdated Components'
  | 'A07:2021-Identification and Authentication Failures'
  | 'A08:2021-Software and Data Integrity Failures'
  | 'A09:2021-Security Logging and Monitoring Failures'
  | 'A10:2021-Server-Side Request Forgery';

export interface Vulnerability {
  id: string;
  category: VulnerabilityCategory;
  severity: VulnerabilitySeverity;
  title: string;
  description: string;
  location: string;
  evidence: string;
  cvss_score: number;
  cwe_id: string | null;
  remediation: string;
  references: string[];
}

export interface SecurityHeaders {
  content_security_policy: string | null;
  x_frame_options: string | null;
  x_content_type_options: string | null;
  strict_transport_security: string | null;
  x_xss_protection: string | null;
  referrer_policy: string | null;
  permissions_policy: string | null;
}

export interface SecurityScanResult {
  id: string;
  project_id: string;
  url: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  vulnerabilities: Vulnerability[];
  headers: SecurityHeaders;
  risk_score: number;
  summary: string;
  scan_duration_ms: number;
  recommendations: string[];
  scan_type: 'quick' | 'standard' | 'deep';
  started_at: string | null;
  completed_at: string | null;
  triggered_by: string | null;
  created_at: string;
}

// Activity System types (for live session tracking)
export interface ActivityLog {
  id: string;
  project_id: string;
  session_id: string;
  activity_type: 'discovery' | 'visual_test' | 'test_run' | 'quality_audit' | 'global_test';
  event_type: 'started' | 'step' | 'screenshot' | 'thinking' | 'action' | 'error' | 'completed' | 'cancelled';
  title: string;
  description: string | null;
  metadata: Json;
  screenshot_url: string | null;
  duration_ms: number | null;
  created_at: string;
}

export interface LiveSession {
  id: string;
  project_id: string;
  session_type: 'discovery' | 'visual_test' | 'test_run' | 'quality_audit' | 'global_test';
  status: 'active' | 'completed' | 'failed' | 'cancelled';
  current_step: string | null;
  total_steps: number;
  completed_steps: number;
  last_screenshot_url: string | null;
  started_at: string;
  completed_at: string | null;
  metadata: Json;
}
